# Generated by Django 4.0.4 on 2022-05-08 09:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_blogs', '0004_alter_category_adder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_blogs.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
