# Generated by Django 4.0.4 on 2022-05-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='no_of_new_category',
        ),
    ]
