# Generated by Django 4.0.4 on 2022-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_profile_no_of_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_new_category',
            field=models.IntegerField(default=0),
        ),
    ]
