# Generated by Django 4.0.4 on 2022-05-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_no_of_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
